#!/bin/bash
set -ex

# Clone agent-sandbox to a temp directory
TMP_DIR=$(mktemp -d)
echo "Cloning agent-sandbox into ${TMP_DIR}"
git clone https://github.com/kubernetes-sigs/agent-sandbox.git "${TMP_DIR}"

pushd "${TMP_DIR}"

# Get project to construct image prefix
PROJECT_ID=$(gcloud config get project)
IMAGE_PREFIX="gcr.io/${PROJECT_ID}/"

echo "Building and pushing images with prefix ${IMAGE_PREFIX}"
./dev/tools/push-images --image-prefix="${IMAGE_PREFIX}" --controller-only

echo "Deploying manifests to kubernetes with prefix ${IMAGE_PREFIX}"
# Install the "extension" version of the manifest
./dev/tools/deploy-to-kube --image-prefix="${IMAGE_PREFIX}" --extensions

popd
rm -rf "${TMP_DIR}"

echo "agent-sandbox installation complete."
