#!/bin/bash
set -ex

# Clone service-portals to a temp directory
TMP_DIR=$(mktemp -d)
echo "Cloning service-portals into ${TMP_DIR}"
git clone https://github.com/gke-labs/service-portals.git "${TMP_DIR}"

pushd "${TMP_DIR}"

# Get project to construct image prefix
PROJECT_ID=$(gcloud config get project)
IMAGE_PREFIX="gcr.io/${PROJECT_ID}"

echo "Deploying to Kubernetes using ap..."
IMAGE_PREFIX="${IMAGE_PREFIX}" go run github.com/gke-labs/gke-labs-infra/ap@latest deploy //...

popd
rm -rf "${TMP_DIR}"

echo "service-portals installation complete."
